---
- name: install nodejs
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: add apt keys
      apt_key: url={{ item }}
      with_items:
        - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: add repos
      apt_repository: repo={{ item }} update_cache=yes
      with_items:
        - deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main
        - deb https://dl.yarnpkg.com/debian/ stable main

    - name: install packages
      apt: name={{ item }}
      with_items:
        - nodejs
        - yarn

    - name: Install git
       apt:
         name: git
         state: present
      become: yes
